baseurl: /~billhowe/
exclude: [README.md, deploy.sh]
highlighter: pygments
plugins: ['jekyll/scholar']

scholar:
  style: ieee
  locale: en

  repository: publications/pdfs
 
  sort_by: year,month
  order: descending

  group_by: none
  group_order: descending

  source: ./publications
  bibliography: billhowe.bib
  bibliography_template: bibliography

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
